name: NRStations Pull Request Actions

# Trigger on pull request to develop
on:
  pull_request:
    branches:
      - 'master'

jobs:

  PRTest:
    name: PR Checks
    runs-on: ubuntu-latest

    steps:
      # step checkout code
      - name: Clone Repo
        uses: actions/checkout@v2

      # step set up JDK
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build all artifacts
        run: ./gradlew build

